<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Transaction extends \App\Entity\Transaction implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'nomE', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'prenomE', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'cniE', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'nomB', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'prenomB', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'cniB', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'dateTrans', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'envoi', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'retrait', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'telephoneE', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'telephoneB', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'montant', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'montantpaye', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'codeTrans'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'nomE', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'prenomE', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'cniE', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'nomB', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'prenomB', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'cniB', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'dateTrans', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'envoi', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'retrait', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'telephoneE', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'telephoneB', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'montant', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'montantpaye', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'codeTrans'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Transaction $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomE(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomE', []);

        return parent::getNomE();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomE(?string $nomE): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomE', [$nomE]);

        return parent::setNomE($nomE);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomE(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomE', []);

        return parent::getPrenomE();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomE(?string $prenomE): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomE', [$prenomE]);

        return parent::setPrenomE($prenomE);
    }

    /**
     * {@inheritDoc}
     */
    public function getCniE(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCniE', []);

        return parent::getCniE();
    }

    /**
     * {@inheritDoc}
     */
    public function setCniE(?string $cniE): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCniE', [$cniE]);

        return parent::setCniE($cniE);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomB(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomB', []);

        return parent::getNomB();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomB(?string $nomB): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomB', [$nomB]);

        return parent::setNomB($nomB);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomB(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomB', []);

        return parent::getPrenomB();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomB(?string $prenomB): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomB', [$prenomB]);

        return parent::setPrenomB($prenomB);
    }

    /**
     * {@inheritDoc}
     */
    public function getCniB(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCniB', []);

        return parent::getCniB();
    }

    /**
     * {@inheritDoc}
     */
    public function setCniB(?string $cniB): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCniB', [$cniB]);

        return parent::setCniB($cniB);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateTrans(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateTrans', []);

        return parent::getDateTrans();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateTrans(\DateTimeInterface $dateTrans): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateTrans', [$dateTrans]);

        return parent::setDateTrans($dateTrans);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnvoi(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnvoi', []);

        return parent::getEnvoi();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnvoi(?string $envoi): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnvoi', [$envoi]);

        return parent::setEnvoi($envoi);
    }

    /**
     * {@inheritDoc}
     */
    public function getRetrait(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRetrait', []);

        return parent::getRetrait();
    }

    /**
     * {@inheritDoc}
     */
    public function setRetrait(?string $retrait): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRetrait', [$retrait]);

        return parent::setRetrait($retrait);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephoneE(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephoneE', []);

        return parent::getTelephoneE();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephoneE(?string $telephoneE): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephoneE', [$telephoneE]);

        return parent::setTelephoneE($telephoneE);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephoneB(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephoneB', []);

        return parent::getTelephoneB();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephoneB(string $telephoneB): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephoneB', [$telephoneB]);

        return parent::setTelephoneB($telephoneB);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontant(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontant', []);

        return parent::getMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontant(?int $montant): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontant', [$montant]);

        return parent::setMontant($montant);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantpaye(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantpaye', []);

        return parent::getMontantpaye();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantpaye(?int $montantpaye): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantpaye', [$montantpaye]);

        return parent::setMontantpaye($montantpaye);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeTrans(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeTrans', []);

        return parent::getCodeTrans();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeTrans(?string $codeTrans): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeTrans', [$codeTrans]);

        return parent::setCodeTrans($codeTrans);
    }

}
