<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV2thq6K\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV2thq6K/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV2thq6K.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV2thq6K\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerV2thq6K\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'V2thq6K',
    'container.build_id' => '8a749ed2',
    'container.build_time' => 1566925539,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV2thq6K');
