<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDy41lj2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDy41lj2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDy41lj2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDy41lj2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDy41lj2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Dy41lj2',
    'container.build_id' => 'f4ccc0c5',
    'container.build_time' => 1566830996,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDy41lj2');
