<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ5VTGmL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ5VTGmL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ5VTGmL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ5VTGmL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZ5VTGmL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Z5VTGmL',
    'container.build_id' => 'dea66f5d',
    'container.build_time' => 1567759193,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ5VTGmL');
